name: Append Signup to CSV

on:
  repository_dispatch:
    types: [add-signup]

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Append to CSV
        run: |
          echo "${{ github.event.client_payload.csv_line }}" >> signups.csv

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add signups.csv
          git commit -m "Add signup"
          git push
