name: Append Signup to CSV

on:
  repository_dispatch:
    types: [add-signup]

jobs:
  append-to-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Append CSV line to file
        run: |
          echo "${{ github.event.client_payload.csv_line }}" >> signups.csv

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add signups.csv
          git commit -m "Add signup via Netlify"
          git push
